id: 149e55f52a0a42908e44546cc5b9dda6
initial_creation_type: ocr
source_metadata:
  volumes:
    07d5bb76c8f5467a96e0a4781c28621f:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: སཱཙྪ་ལྔ་གདབ་པའི་ཆོ་ག།
      total_pages: 1044
      volume_number: 38
