id: DA821D024
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:14:39+00:00'
last_modified: '2022-05-26T12:39:40.010257+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    c264:
      image_group_id: I1PD95883
      title: སཱཙྪ་ལྔ་གདབ་པའི་ཆོ་ག།
      total_pages: 1044
      order: 38
      base_file: c264.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
